spring:
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  datasource:
    url: jdbc:h2:mem:test
    username: lukasz
    password: lukasz
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8081
